# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    default_config: pasaia_config
    configs:
        pasaia_config:
            language: eu
            toolbar:
                - [Bold, Italic, Underline, Strike, Blockquote, -, Cut, Copy, Paste,
                   PasteText, PasteFromWord, -, Undo, Redo, -,
                   NumberedList, BulletedList, -, Outdent, Indent, -,
                   -, Image, Link, Unlink, Table]
                - [Format, Maximize, Source]
            uiColor: "#ffffff"
        full:
            language: eu
            toolbar: full
