vich_uploader:
    db_driver: orm

    mappings:
        pdf_mapping:
            uri_prefix: /uploads/PDF
            upload_destination: '%kernel.project_dir%/public/uploads/PDF'
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y' # will create directory "2018/23/09" for current date "2018-09-23"
#                    date_time_property: uploadTimestamp # see above example
            inject_on_load: false # should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File
            delete_on_update: true # should the file be deleted when a new file is uploaded
            delete_on_remove: true # should the file be deleted when the entity is removed
