version:  '3.7'
services:
    db:
        container_name: aktak_db
        image: mysql:8.0
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
            MYSQL_USER: ${DOCKER_MYSQL_USER}
            MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_erabakiak:/var/lib/mysql
        ports:
        - '3306:3306'

    app:
        container_name: aktak_app
        env_file: ./.env
        build:
            context: .
            dockerfile: ./docker/php/dev/Dockerfile
            args:
                - USER_ID=${USER_ID}
        depends_on:
          - db
          - redis
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - '.:/app'
            - './docker/php/dev/.zsh_history:/home/appuser/.zsh_history:rw'
        working_dir: /app

    nginx:
        container_name: aktak_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - './:/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - app
        ports:
            - 80:80

    redis:
        container_name: aktak_redis
        image: redis:alpine
        ports:
            - "6380:637"
        volumes:
            - redis_erabakiak:/data

    adminer:
        image: adminer
        ports:
            - "8080:8080"

volumes:
    mysql_erabakiak:
    redis_erabakiak:
