version:  '3.7'
services:
    db:
        command: ["--default-authentication-plugin=mysql_native_password"]
        container_name: aktak_db
        environment:
            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
            MYSQL_USER: ${DOCKER_MYSQL_USER}
            MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
        image: mysql:8.0
        networks:
            - erabakiak_net
        ports:
            - '3306:3306'
        restart: on-failure
        volumes:
            - mysql_erabakiak:/var/lib/mysql

    app:
        container_name: aktak_app
        depends_on:
            - db
            - redis
        image: ikerib/aktak_app:1.4
        networks:
            - erabakiak_net
        restart: on-failure
        working_dir: /app

    nginx:
        container_name: aktak_nginx
        depends_on:
            - app
        image: ikerib/aktak_nginx:1.4
        networks:
            - erabakiak_net
        ports:
            - 80:80
            - 443:443
        restart: on-failure

    redis:
        container_name: aktak_redis
        image: redis:alpine
        networks:
            - erabakiak_net
        ports:
            - "6380:637"
        restart: on-failure
        volumes:
            - redis_erabakiak:/data

volumes:
    mysql_erabakiak:
    redis_erabakiak:
    app_erabakiak:

networks:
    erabakiak_net:
        ipam:
            config:
                - subnet: 172.177.0.0/16
